module Bulma
  module Components
    module Pagination
      class PrevComponent < ApplicationComponent
        @name: untyped?
        @options: untyped?
        @disabled: bool?
        def initialize: (?untyped?, ?untyped?, ?disabled: bool?, **untyped) -> void
      end
    end
  end
end
