module Bulma
  module Components
    module Card
      module Header
        class TitleComponent < ApplicationComponent
          @centered: bool?
          @text: String?

          def initialize: (?String? text, ?centered: bool?, **untyped html_attributes) -> void
        end
      end
    end
  end
end
