module Bulma
  module Elements
    module Button
      class MailComponent < Button::BaseComponent
        @email_address: untyped?
        @name: untyped?
        def initialize: (?untyped?, ?untyped?, **untyped) -> void
      end
    end
  end
end
