module Bulma
  module Components
    module Dropdown
      module Menu
        class LinkComponent < ItemComponent
          @name: untyped?
          @options: untyped?
          def initialize: (?untyped?, ?untyped?, **untyped) -> void
        end
      end
    end
  end
end
