module Bulma
  module Elements
    class IconComponent < Bulma::ApplicationComponent
      type size = :small | :normal | :medium | :large
      @size: size?
      @left: bool?
      def initialize: (?size: size?, ?left: bool?, **untyped) -> void
    end
  end
end
