module Bulma
  module Elements
    module Tag
      class PhoneComponent < BaseComponent
        @phone_number: untyped?
        @name: untyped?
        def initialize: (?untyped?, ?untyped?, **untyped) -> void
      end
    end
  end
end
